name: "Update binaries"

on:
  schedule:
    # run at midnight
    - cron: "0 0 * *"
  push:
    paths:
      - "data/firmwareRepositories.csv"
      - "data/read.sh"
  workflow_dispatch:

jobs:
  update-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Check if new release
        id: repos
        run: |
          # parse url from csv, this is a test
          # IDEA: call api, save date of release, if release is higher then download, if not skip 
          # URL="https://api.github.com/repos/DevKitty-io/scriptkitty/releases/latest"
          cd data/
          ./read.sh
